[package]
name = "payment_contract"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
casper-contract = "1.1.1"
casper-types = "1.1.1"

[[bin]]
name = "wallet_contract"
path = "src/wallet_contract.rs"
bench = false
doctest = false
test = false

[[bin]]
name = "send_tokens"
path = "src/send_tokens.rs"
bench = false
doctest = false
test = false

[[bin]]
name = "collect"
path = "src/collect.rs"
bench = false
doctest = false
test = false

[features]
default = ["casper-contract/std", "casper-types/std", "casper-contract/test-support"]

[profile.release]
lto = true
